version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "3b:0d:1d:0c:81:81:50:e7:e6:a1:cd:56:00:ce:7d:0b"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push https://github.com/beatrice-yu/lhl-scheduler-proj.git master:production

workflows:
  version: 2
  test:
    jobs:
      - build